### ISSUE TITLE
/serv-freeze avaible for every player

### ISSUE THREAD

**Issue by ImBehinYa** [QPCrummer/Slumber#1]
/serv-freeze avaible for every player and not anly for OPs

**Comment by QPCrummer** [comment]
@ImBehinYa I can’t believe I missed this. Never really thought about it because I always used a permission mod. It is an easy fix, so I plan to have it fixed by tomorrow. Thanks for the issue!

**Comment by ImBehinYa** [comment]
Great

**Comment by QPCrummer** [comment]
@ImBehinYa I pushed the fix for your issue here https://modrinth.com/mod/slumber/version/1.0.1

Enjoy!

**Comment by ImBehinYa** [comment]
Thank you really love the mod
