### ISSUE TITLE
Add more info about deep freezing into README/Modrinth page

### ISSUE THREAD

**Issue by UmeSmoothie** [QPCrummer/Slumber#10]
Add more info about deep freezing into README/Modrinth page:

- what are the side effects?
- how is that different from the default sleep?
- is it safe?
- will it unfreeze in the same way if the deep freezing is enabled?

It doesn't seem to be that simple when it comes to finding info about the feature.

**Comment by QPCrummer** [comment]
Hello! The “deep freeze” feature has been removed for modern versions of Slumber as it was pretty much useless. It came from Carpet’s “/tick” code. 
Basically its use was to eliminate every single ticking feature in the game (besides networking and a few others). The main thing it removes is chunk loading, but that’s completely useless if the point of slumber is to work when no one is online.

**Comment by kossnikita** [comment]
Please add to the README what this mod does. I mean the specific features it has. What does this mod disable and what is running during freezing?
