### ISSUE TITLE
Mixin apply for Slumber 1.3.0 beta.1 fails

### ISSUE THREAD

**Issue by Ninju4821** [QPCrummer/Slumber#14]
## Log Files: [latest.log](https://github.com/user-attachments/files/17687863/latest.log)
- See line(s) 158, 194,  231, 268, 304, 339,  375; timestamp(s) 13:44:22 and 13:44:23
- Note: line 156 main/WARN is expected, and likely not related.

## My assessment (may be incorrect):
Based on error message, I believe a function in code was improperly set void or null, and this caused an unintended loop in code causing the server to timeout in initialization.

## Other information:
- Server Ram: 2GB dedicated of 4GB
- MC Version: 1.21.3
- Fabric Version: 0.16.9
- Java Version:
 -- openjdk 21.0.4 2024-07-16
 -- OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
 -- OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)
- Server OS Version: 
 -- Ubuntu 24.04.1 LTS
 -- Linux 6.8.0-48-generic
 -- x86-64

**Comment by QPCrummer** [comment]
I’ll have it fixed this weekend. I need to do some rewriting too because I didn’t know that Mojang actually added “slumbering” into the game in 1.21

**Comment by Ninju4821** [comment]
How's this coming? Me and my friends have been waiting for this mod fix before getting our private server up and running agian. Any help is appreciated

**Comment by QPCrummer** [comment]
I have just fixed this. I am pushing a new beta in a few minutes

**Comment by Ninju4821** [comment]
Ok! Thanks for your help!

**Comment by QPCrummer** [comment]
Here is the new version https://modrinth.com/mod/slumber/version/1.3.0-beta.2
Or on the Github release
