### ISSUE TITLE
Stop cannot be used to shut down the server normally after installing the module.

### ISSUE THREAD

**Issue by oceanst1** [QPCrummer/Slumber#2]
After the module is installed on the 1.19.4 farbic server, when all players quit the server and the server is in a frozen state, it is impossible to use stop to shut down the server normally in the background.

**Comment by oceanst1** [comment]
![20230404214328](https://user-images.githubusercontent.com/54645053/229812530-20315159-1b1e-481c-a667-12eb58911fe6.jpg)

**Comment by oceanst1** [comment]
[latest.zip](https://github.com/Tater-Certified/Slumber/files/11149210/latest.zip)

**Comment by QPCrummer** [comment]
@oceanst1 This was completely my fault because I failed to shutdown a thread. The latest version fixes this. Thank you so much for reporting this as it may have actually effected a ton of people!

https://github.com/Tater-Certified/Slumber/releases/tag/1.1.0-1.19.4
