### ISSUE TITLE
Deeply: false when Complete-Freeze: true

### ISSUE THREAD

**Issue by NopeProsOnly** [QPCrummer/Slumber#3]
```yml
#Wed Jun 14 09:07:46 EDT 2023
freeze-delay-seconds=20
config-version=1.1
safe-starting=true
complete-freeze=true
toggle=true
```
```
serv-freeze
[09:31:08] [Server thread/INFO] (Minecraft) Enabled: true, Frozen: true, Deeply: false
```
I do have carpet installed.

**Comment by QPCrummer** [comment]
While this technically is an issue, deep freeze does basically nothing in terms of performance, though could potentially cause issues loading chunks when a player joins. Deep freeze is set to be removed for the 1.20 updated, and potentially back ported to the older versions if there is demand for it. 
Tldr: The deep freeze is useless, so there is no need to enable it
